# TODO get self ip 
import socket

HOST = '0.0.0.0'
PORT = 9998

DB_HOST = '127.0.0.1'
DB_PORT = 3306
DB_USER = ''
DB_PWD = ''
DB_NAME = ''

HTTP_REQUEST_TIMEOUT = 120
HTTP_CONNECT_TIMEOUT = 60

REDIS_HOST = '127.0.0.1'
REDIS_PORT = 6379

TASK_WAIT_TOO_MUCH_TIME = 90

DEBUG_MODE = True

PROJECT_NAME = 'fishing'
INSTANCE_NAME = 'server'

MAX_WAIT_SECONDS_BEFORE_SHUTDOWN = 3

MEINV_INDEX_DISPLAY_NUM = 36
MEINVPIC_INDEX_DISPLAY_NUM = 5
GAOXIAOVIDEO_INDEX_DISPLAY_NUM = 8

UPLOAD_DIR = '/tmp/'

RISK_RATE = 0.5
PROFIT_RATE = 0.1
